theme: minima
title: Philip's HelpHub Blog
author: Philip ZENG
email: 892542757@qq.com
description: > # this means to ignore newlines until "baseurl:"
  The bloger will share his experience of website and program developing during his time at HelpHub

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Philip-ZENG # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
